#pragma once

// Stepper driver for one TMC2209 axis. STEP pulses are generated by the ESP32
// RMT peripheral (hardware-timed, jitter-free) rather than bit-banging, which
// frees the CPU and keeps step timing precise. DIR is a plain GPIO; EN and the
// MS1/MS2 microstep pins are shared/configured at the board level.
//
// Velocity ramping (trapezoidal) is delegated to the host-tested RampGenerator;
// this class only translates the ramped step rate into an RMT pulse train.

#include <Arduino.h>

#include <cstdint>

#include "ramp_generator.h"

class MotorDriver {
 public:
  MotorDriver(uint8_t step_pin, uint8_t dir_pin, float max_accel_steps_s2);

  void begin();
  void setTargetSpeed(float steps_per_sec);  // signed; sign chooses direction
  void update(float dt);                      // advance ramp, refresh RMT output
  void stop();                                // ramp target to zero

  float currentSpeed() const { return ramp_.current(); }

 private:
  void applyFrequency(float steps_per_sec);

  uint8_t step_pin_;
  uint8_t dir_pin_;
  RampGenerator ramp_;
  rmt_obj_t* rmt_ = nullptr;
  bool loop_active_ = false;
};
